version: '2'

services:
  mysql:
    image: 'mysql:5.6'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  application:
    depends_on:
      - 'mysql'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/cabins'
    env_file:
      - 'cabins.env'

  sidekiq:
    depends_on:
      - 'mysql'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/cabins'
    env_file:
      - 'cabins.env'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/cabins'
    env_file:
      - 'cabins.env'

volumes:
  redis:
  mysql:
