default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_development?') %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_staging?') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_production?') %>
